CARTERA_CATEGORICAL_COLUMNS = [
    'CALIFICACION_CIERRE',
    'COD_LINEA',
    'LINEA',
    'COD_MODALIDAD',
    'MODALIDAD',
    'MUNICIPIO_CLIENTE',
    'REGION',
    'PERIODICIDAD_PAGO',
    'TIPO_CREDITO',
    'TIPO_UBICACION',
]

CARTERA_COLOCACION_COLUMNS = [
    'COD_LINEA',
    'COD_MODALIDAD',
    'FECHA_APROBA',
    'FECHA_DESEMBOLSO',
    'FECHA_SOLICITUD',
    'LINEA',
    'MONTO',
    'TASA_ANUAL',

    # 'MODALIDAD',  # see inconsistencies in cleaning_cartera
    # 'REGION',  # see inconsistencies in cleaning_cartera
    # 'TIPO_CREDITO',  # see inconsistencies in cleaning_cartera

    # see considerations in cleaning_cartera
    # 'PERIODICIDAD_PAGO',
    # 'TASA_PERIODICA',
    # 'VALOR_CUOTA',

    # NRO_CUOTAS, CUOTAS_PACTADAS
    # 'SUCURSAL_COD',  # see considerations in cleaning_cartera
]

CARTERA_DISCARDED_COLUMNS = [
    'GARANTIA_REAL',
    'NRO_SOLICITUD',
    'PAGARE',
    'TIPO'
]

CARTERA_USELESS_COLUMNS = [
    'BUS_REGION',
    'CEDULA',
    'CELULAR',
    'CORREO',
    'DIRECCION',
    'EDAD',
    'EJECUTIVO_ACTUAL',
    'ESTADO_CIVIL',
    'ESTRATO',
    'FACTORRH',
    'FECHA_NACIMIENTO',
    'FECHA_UTL_ACTUALIZACION',
    'GENERO',
    'MUJER_CABEZA',
    'MUNICIPIO',
    'NIVEL_ESTUDIOS',
    'NOMBRE',
    'PROFESION',
    'RANGO_PAGO',
    'REGION_1',
    'REGION_REAL',
    'SUCURSAL',
    'SUCURSALES',
    'SUCURSAL_1',
    'TEL_FIJO'
]

COLOCACION_CATEGORICAL_COLUMNS = [
    'COD_DESTINACION',
    'DESTINACION',
    'COD_LINEA',
    'LINEA',
]

COLOCACION_CLIENT_COLUMNS = [
    'EDAD',
    'ESTADO_CIVIL',
    'ESTRATO',
    'FECHA_NACIMIENTO',
    'GENERO',
    'NIVEL_ESTUDIOS',
    'PROFESION',
    'TIPO_UBICACION',
    'TIPO_VIVIENDA',
]

COLOCACION_DISCARDED_COLUMNS = [
    'CEDULA',
    'CELULAR',
    'COD_USUARIO_APR',
    'CORREO',
    'DIRECCION',
    'DOC_CONTABILIZA',
    'ESTADO',
    'EST_SOLICITUD',
    'IDENTI_EJECUTIVO',
    'NOMBRE',
    'NOMBRE_EJECUTIVO',
    'NOMBRE_USUARIO',
    'SOLICITUD',
    'TEL_FIJO',
    'TIPO_DOCUMENTO',
    'TIPO_OBLIGA'
]

COLOCACION_LOCATION_COLUMNS = [
    'MUNICIPIO',
    'SUCURSAL',
    'SUCURSAL_COD',
    'SUCURSAL_CONTABILIZA',
    'REGION',
]

CONTACTO_DISCARDED_COLUMNS = [
    'ADMINISTRA_RECURSOS_PUBLICOS',
    'ASIGNADO_A',
    'AUTORIZA_EL_ENVIO_DE_INFORMACION_POR_MEDIO_DE_CORREO_ELCTRONICO',
    'AUTORIZA_LA_CONSULTA_EN_LAS_CENTRALES_DE_RIESGO',
    'BANCO_MONEDA_EXTRANJERA',
    'BARRIO_COMERCIAL',
    'BARRIO_RESIDENCIA',
    'CENTRO_DE_COSTO',
    'CIUDAD_COMERCIAL',
    'CIUDAD_EMPRESA',
    'CIUDAD_RESIDENCIA',
    'CUENTA_MONEDA_EXTRANJERA',
    'DECLARA_RENTA',
    'DESCRIPCION_DE_LAS_OPERACIONES_EN_MONEDA_EXTRANJERA',
    'DESCRIPCION_OTROS_INGRESOS',
    'DIRECCION_COMERCIAL',
    'DIRECCION_DE_RESIDENCIA',
    'DIRECCION_EMPRESA',
    'DIR_CORRESPONDENCIA',
    'EGRESOS_MENSUALES',
    'EMAIL',
    'EMPRESA_DONDE_TRABAJA',
    'ENTIDAD_FINANCIERA',
    'FAX',
    'FAX_EMPRESA',
    'FECHA_DE_EXPEDICION_CEDULA',
    'INGRESO_MENSUAL',
    'JORNADA_LABORAL',
    'LUGAR_DE_EXPEDICION',
    'MEDIO_DE_PAGO',
    'MONEDA',
    'MOVIL',
    'NATURALEZA',
    'NOMBRE_DEL_CARGO_QUE_DESEMPENA_EN_LA_EMPRESA',
    'OTROS_INGRESOS',
    'PAIS_MONEDA_EXTRANJERA',
    'PERSONA_FALLECIDA',
    'POBLACION_VULNERABLE',
    'POSEE_CUENTAS_EN_MONEDA_EXTRANJERA',
    'REALIZA_OPERACIONES_EN_MONEDA_EXTRANJERA',
    'REGIMEN_DE_IMPUESTOS',
    'REGIMEN_DE_IVA',
    'REGIMEN_DE_RENTA',
    'REGIONAL',
    'TELEFONO_EMPRESA',
    'TELEFONO_PARTICULAR',
    'TIPO_DE_CONTRATO',
    'TIPO_DE_CONTRIBUYENTE',
    'TIPO_DE_CUENTA_BANCARIA',
    'UBICACION_2',
    'VALOR_OTROS_DESCUENTOS_DE_NOMINA',
    'VENCIMIENTO_DEL_CONTRATO'
]

COMMUNICATION_CONTACT_COLUMNS = [
    'CELULAR',
    'CORREO',
    'TEL_FIJO',
    'TEL_NEGOCIO'
]

LOCATION_NONCATEGORICAL_COLUMNS = [
    'BARRIO_NEGOCIO',
    'DIRECCION'
]

NEGOCIO_CLIENT_COLUMNS = [
    'ACTIVIDAD',
]

NEGOCIO_PIVOTED_COLUMNS = [
    'CANTIDAD_DE_INVENTARIO_1',
    'CANTIDAD_DE_INVENTARIO_2',
    'CANTIDAD_DE_INVENTARIO_3',
    'CANTIDAD_DE_INVENTARIO_4',
    'CANTIDAD_DE_INVENTARIO_5',
    'CANTIDAD_DE_INVENTARIO_6',
    'DESCRIPCION_DEL_ACREEDOR_1',
    'DESCRIPCION_DEL_ACREEDOR_2',
    'DESCRIPCION_DEL_ACREEDOR_3',
    'DESCRIPCION_DEL_ACREEDOR_4',
    'DESCRIPCION_DEL_ACTIVO_FIJO_1',
    'DESCRIPCION_DEL_ACTIVO_FIJO_2',
    'DESCRIPCION_DEL_ACTIVO_FIJO_3',
    'DESCRIPCION_DEL_PRODUCTO_1',
    'DESCRIPCION_DEL_PRODUCTO_2',
    'DESCRIPCION_DEL_PRODUCTO_3',
    'DESCRIPCION_DEL_PRODUCTO_4',
    'DESCRIPCION_DEL_PRODUCTO_5',
    'DESCRIPCION_DEL_PRODUCTO_6',
    'DESCRIPCION_DEL_PRODUCTO_QUE_COMERCIALIZA_1',
    'DESCRIPCION_DEL_PRODUCTO_QUE_COMERCIALIZA_2',
    'DESCRIPCION_DEL_PRODUCTO_QUE_COMERCIALIZA_3',
    'DESCRIPCION_DEL_PRODUCTO_QUE_COMERCIALIZA_4',
    'DESCRIPCION_DEL_PRODUCTO_QUE_COMERCIALIZA_5',
    'DESTINO_DEL_PASIVO_1',
    'DESTINO_DEL_PASIVO_2',
    'DESTINO_DEL_PASIVO_3',
    'DESTINO_DEL_PASIVO_4',
    'ENTIDAD_CON_LA_CUAL_TIENE_LA_HIPOTECA_O_LA_PRENDA_1',
    'ENTIDAD_CON_LA_CUAL_TIENE_LA_HIPOTECA_O_LA_PRENDA_2',
    'ENTIDAD_CON_LA_CUAL_TIENE_LA_HIPOTECA_O_LA_PRENDA_3',
    'FECHA_DE_ADQUISICION_DEL_ACTIVO_FIJO_1',
    'FECHA_DE_ADQUISICION_DEL_ACTIVO_FIJO_2',
    'FECHA_DE_ADQUISICION_DEL_ACTIVO_FIJO_3',
    'FRECUENCIA_DEL_VALOR_DE_LA_CUOTA_1',
    'FRECUENCIA_DEL_VALOR_DE_LA_CUOTA_2',
    'FRECUENCIA_DEL_VALOR_DE_LA_CUOTA_3',
    'FRECUENCIA_DEL_VALOR_DE_LA_CUOTA_4',
    'INDICADOR_SI_EL_ACTIVO_FIJO_ES_GARANTIA_1',
    'INDICADOR_SI_EL_ACTIVO_FIJO_ES_GARANTIA_2',
    'INDICADOR_SI_EL_ACTIVO_FIJO_ES_GARANTIA_3',
    'INDICADOR_SI_LOS_ACTIVOS_FIJOS_AFECTAN_AL_NEGOCIO_O_SON_DE_LOS_BIENES_DE_LA_UNIDAD_FAMILIAR_1',
    'INDICADOR_SI_LOS_ACTIVOS_FIJOS_AFECTAN_AL_NEGOCIO_O_SON_DE_LOS_BIENES_DE_LA_UNIDAD_FAMILIAR_2',
    'INDICADOR_SI_LOS_ACTIVOS_FIJOS_AFECTAN_AL_NEGOCIO_O_SON_DE_LOS_BIENES_DE_LA_UNIDAD_FAMILIAR_3',
    'INGRESO_ABRIL',
    'INGRESO_AGOSTO',
    'INGRESO_DICIEMBRE',
    'INGRESO_ENERO',
    'INGRESO_FEBRERO',
    'INGRESO_JULIO',
    'INGRESO_JUNIO',
    'INGRESO_MARZO',
    'INGRESO_MAYO',
    'INGRESO_NOVIEMBRE',
    'INGRESO_OCTUBRE',
    'INGRESO_SEPTIEMBRE',
    'MODELO_DEL_VEHICULO_1',
    'MODELO_DEL_VEHICULO_2',
    'MODELO_DEL_VEHICULO_3',
    'MONTO_DE_LA_DEUDA_1',
    'MONTO_DE_LA_DEUDA_2',
    'MONTO_DE_LA_DEUDA_3',
    'MONTO_DE_LA_DEUDA_4',
    'NUMERO_DE_LA_MATRICULA_INMOBILIARIA_EN_CASO_QUE_EL_TIPO_DE_ACTIVO_SEA_INMUEBLES_1',
    'NUMERO_DE_LA_MATRICULA_INMOBILIARIA_EN_CASO_QUE_EL_TIPO_DE_ACTIVO_SEA_INMUEBLES_2',
    'NUMERO_DE_LA_MATRICULA_INMOBILIARIA_EN_CASO_QUE_EL_TIPO_DE_ACTIVO_SEA_INMUEBLES_3',
    'NUMERO_DE_LA_PLACA_EN_CASO_QUE_EL_TIPO_DE_ACTIVOS_SEA_VEHICULO_1',
    'NUMERO_DE_LA_PLACA_EN_CASO_QUE_EL_TIPO_DE_ACTIVOS_SEA_VEHICULO_2',
    'NUMERO_DE_LA_PLACA_EN_CASO_QUE_EL_TIPO_DE_ACTIVOS_SEA_VEHICULO_3',
    'NUMERO_DE_SERIAL_CUANDO_EL_ACTIVO_FIJO_HACE_PARTE_DE_LA_GARANTIA_1',
    'NUMERO_DE_SERIAL_CUANDO_EL_ACTIVO_FIJO_HACE_PARTE_DE_LA_GARANTIA_2',
    'NUMERO_DE_SERIAL_CUANDO_EL_ACTIVO_FIJO_HACE_PARTE_DE_LA_GARANTIA_3',
    'NUMERO_DE_UNIDADES_VENDIDAS_1',
    'NUMERO_DE_UNIDADES_VENDIDAS_2',
    'NUMERO_DE_UNIDADES_VENDIDAS_3',
    'NUMERO_DE_UNIDADES_VENDIDAS_4',
    'NUMERO_DE_UNIDADES_VENDIDAS_5',
    'OBSERVACIONES_DEL_ACTIVO_FIJO_1',
    'OBSERVACIONES_DEL_ACTIVO_FIJO_2',
    'OBSERVACIONES_DEL_ACTIVO_FIJO_3',
    'TIPO_DE_ACTIVO_FIJO_DEL_ESTUDIO_SOCIO-ECONOMICO_1',
    'TIPO_DE_ACTIVO_FIJO_DEL_ESTUDIO_SOCIO-ECONOMICO_2',
    'TIPO_DE_ACTIVO_FIJO_DEL_ESTUDIO_SOCIO-ECONOMICO_3',
    'TIPO_DE_INVENTARIO_1',
    'TIPO_DE_INVENTARIO_2',
    'TIPO_DE_INVENTARIO_3',
    'TIPO_DE_INVENTARIO_4',
    'TIPO_DE_INVENTARIO_5',
    'TIPO_DE_INVENTARIO_6',
    'TIPO_DE_PASIVO_1',
    'TIPO_DE_PASIVO_2',
    'TIPO_DE_PASIVO_3',
    'TIPO_DE_PASIVO_4',
    'VALOR_COMERCIAL_1',
    'VALOR_COMERCIAL_2',
    'VALOR_COMERCIAL_3',
    'VALOR_DEL_COSTO_UNITARIO_DEL_PRODUCTO_1',
    'VALOR_DEL_COSTO_UNITARIO_DEL_PRODUCTO_2',
    'VALOR_DEL_COSTO_UNITARIO_DEL_PRODUCTO_3',
    'VALOR_DEL_COSTO_UNITARIO_DEL_PRODUCTO_4',
    'VALOR_DEL_COSTO_UNITARIO_DEL_PRODUCTO_5',
    'VALOR_DEL_PRECIO_DE_VENTA_POR_UNIDAD_DEL_PRODUCTO_1',
    'VALOR_DEL_PRECIO_DE_VENTA_POR_UNIDAD_DEL_PRODUCTO_2',
    'VALOR_DEL_PRECIO_DE_VENTA_POR_UNIDAD_DEL_PRODUCTO_3',
    'VALOR_DEL_PRECIO_DE_VENTA_POR_UNIDAD_DEL_PRODUCTO_4',
    'VALOR_DEL_PRECIO_DE_VENTA_POR_UNIDAD_DEL_PRODUCTO_5',
    'VALOR_DE_LA_CUOTA_1',
    'VALOR_DE_LA_CUOTA_2',
    'VALOR_DE_LA_CUOTA_3',
    'VALOR_DE_LA_CUOTA_4',
    'VALOR_DE_LA_CUOTA_ACTUAL_1',
    'VALOR_DE_LA_CUOTA_ACTUAL_2',
    'VALOR_DE_LA_CUOTA_ACTUAL_3',
    'VALOR_DE_LA_CUOTA_ACTUAL_4',
    'VALOR_DE_LA_GARANTIA_1',
    'VALOR_DE_LA_GARANTIA_2',
    'VALOR_DE_LA_GARANTIA_3',
    'VALOR_DE_LA_HIPOTECA_O_LA_PRENDA_1',
    'VALOR_DE_LA_HIPOTECA_O_LA_PRENDA_2',
    'VALOR_DE_LA_HIPOTECA_O_LA_PRENDA_3',
    'VALOR_UNITARIO_DEL_INVENTARIO_PARA_EL_ESTUDIO_SOCIO-ECONOMICO_1',
    'VALOR_UNITARIO_DEL_INVENTARIO_PARA_EL_ESTUDIO_SOCIO-ECONOMICO_2',
    'VALOR_UNITARIO_DEL_INVENTARIO_PARA_EL_ESTUDIO_SOCIO-ECONOMICO_3',
    'VALOR_UNITARIO_DEL_INVENTARIO_PARA_EL_ESTUDIO_SOCIO-ECONOMICO_4',
    'VALOR_UNITARIO_DEL_INVENTARIO_PARA_EL_ESTUDIO_SOCIO-ECONOMICO_5',
    'VALOR_UNITARIO_DEL_INVENTARIO_PARA_EL_ESTUDIO_SOCIO-ECONOMICO_6',
]

RENAMING_RAW_COLUMNS_DICT = {
    # "Cod modalidad": "MODALIDAD_COD",  # cartera
    # "Cod_Modalidad": "MODALIDAD_COD",  # colocacion
    "Cod tipo Cliente": "TIPO_CLIENTE_COD",
    "Cod tipoCliente": "TIPO_CLIENTE_COD",  # cartera
    "Cod_tipoCliente": "TIPO_CLIENTE_COD",  # colocacion
    "Codeudores": "CODEUDOR",  # colocacion old
    'Est Civil': 'ESTADO_CIVIL',  # cartera
    'Est_Civil': 'ESTADO_CIVIL',  # colocacion
    "Fecha de Nacimiento": "FECHA_NACIMIENTO",  # contacto
    "Garntia real": "GARANTIA_REAL",  # cartera
    "Garntia_real": "GARANTIA_REAL",  # colocacion old
    "Homologacion Documento de Identidad": "CLIENTE",
    "Nom tipoCliente": "TIPO_CLIENTE",  # cartera
    "Nom_tipoCliente": "TIPO_CLIENTE",  # colocacion
    "Mujer Cabeza de Familia": "MUJER_CABEZA",  # contacto
    "Nivel estudio": "NIVEL_ESTUDIOS",  # cartera
    "Nivel_estudio": "NIVEL_ESTUDIOS",  # colocacion old
    "Nivel de Estudios": "NIVEL_ESTUDIOS",  # contacto
    "No Obligación": "OBLIGACION",  # castigo
    "Sucurs": "SUCURSAL_COD",
    "Cod_Sucursal": "SUCURSAL_COD",
    "Periodicidad": "PERIODICIDAD_PAGO",  # colocacion old
    "Profesión u Oficio": "PROFESION",  # contacto
    "Saldo Obligacion": "SALDO",
    "Saldo_Obligacion": "SALDO",
    "Sector": "TIPO_UBICACION",
    # "Sucursal Real": "SUCURSAL",
    # "Sucursal.1": "SUCURSAL",
    # "Sucursales": "SUCURSAL",
    "Tasa": "TASA_ANUAL",
    "Tasa N.A.M.V": "TASA_ANUAL",
    "Tipo de Vivienda": "TIPO_VIVIENDA",  # contacto
    "Ubicacion": "TIPO_UBICACION",
    "Ubicacio cliente": "TIPO_UBICACION",
    "Ubicacio cliente": "TIPO_UBICACION",
    "ubicacio cliente": "TIPO_UBICACION",
    "ubicacio_cliente": "TIPO_UBICACION",
    "Vencimiento Final": "FECHA_VENCIMIENTO_FINAL",  # cartera
    "ï»¿Tipo": "TIPO",
}

SENSITIVE_COLUMNS = [
    'CEDULA',
    'IDENTI_EJECUTIVO',
]


TIPO_VIVIENDA_CATEGORIES = [
    'ARRIENDO',
    'FAMILIAR',
    'HIPOTECA',
    'OTRA',
    'PROPIA',
    'SIN_VIVIENDA',
]